- README.md
> adding download section to README.md file

- library/src/androidTest/java/com/github/pwittchen/prefser/library/PrefserTest.java
- library/src/main/java/com/github/pwittchen/prefser/library/Prefser.java
> adding null-check for getter with default value

- app-dagger/app-dagger.iml
- app-dagger/build.gradle
- app/app.iml
- app/build.gradle
- library/build.gradle
- library/library.iml
> change min sdk to 9

- gradle.properties
> prepare for release of 1.0.2

- .idea/gradle.xml
- app-dagger/app-dagger.iml
- app/app.iml
- library/build.gradle
- library/library.iml
- library/src/androidTest/java/com/github/pwittchen/prefser/library/PrefserTest.java
- prefser.iml
Unit Tests were refatored. Now they use AndroidJUnit4 instrumentation test runner from [Android Test Kit](https://android-test-kit.googlecode.com/git/docs/javadocs/testing-support-lib-0.1-javadoc/reference/android/support/test/runner/AndroidJUnit4.html) and [Google Truth](https://github.com/google/truth) for assertions. More information about test runner can be found in [its user guide](https://code.google.com/p/android-test-kit/wiki/AndroidJUnitRunnerUserGuide).
> applying AndroidJUnit4 runner and truth library for UT

- README.md
- app-dagger/src/main/java/com/github/pwittchen/prefser/app/dagger/MainActivity.java
- app/src/main/java/com/github/pwittchen/prefser/app/MainActivity.java
- library/src/main/java/com/github/pwittchen/prefser/library/Prefser.java
Adding possibility to observe single shared preference with a specified key.
> Add getObservable() methods

- gradle.properties
> updating library version to 1.0.4

- README.md
> updating library version to 1.0.4 in README.md

- library/build.gradle
- library/src/androidTest/java/com/github/pwittchen/prefser/library/PrefserTest.java
- library/src/main/java/com/github/pwittchen/prefser/library/GsonConverter.java
- library/src/main/java/com/github/pwittchen/prefser/library/JsonConverter.java
- library/src/main/java/com/github/pwittchen/prefser/library/Prefser.java
> Json converter

- README.md
- app-dagger/src/main/java/com/github/pwittchen/prefser/app/dagger/AndroidModule.java
- app-dagger/src/main/java/com/github/pwittchen/prefser/app/dagger/BaseActivity.java
- app-dagger/src/main/java/com/github/pwittchen/prefser/app/dagger/BaseApplication.java
- app-dagger/src/main/java/com/github/pwittchen/prefser/app/dagger/MainActivity.java
- app-preference-activity/src/main/java/com/example/myapplication/MainActivity.java
- app-preference-activity/src/main/java/com/example/myapplication/SettingsActivity.java
- app/src/main/java/com/github/pwittchen/prefser/app/MainActivity.java
- library/src/androidTest/java/com/github/pwittchen/prefser/library/PrefserTest.java
- library/src/main/java/com/github/pwittchen/prefser/library/GsonConverter.java
- library/src/main/java/com/github/pwittchen/prefser/library/JsonConverter.java
- library/src/main/java/com/github/pwittchen/prefser/library/Prefser.java
> adding getAndObserve(...) method

- gradle.properties
> upgrading version to 1.0.5

- library/src/androidTest/java/com/github/pwittchen/prefser/library/PrefserTest.java
- library/src/main/java/com/github/pwittchen/prefser/library/Prefser.java
- Fix not keeping reference to listener when Observable instance is reused.
- Fix not unregistering listener, which causes onNext() even after unsubscribe().
> Fix onChangeListener not properly registered/unregistered

- app-preference-activity/src/main/java/com/github/pwittchen/prefser/app/preference/SettingsActivity.java
- app/src/main/java/com/github/pwittchen/prefser/app/MainActivity.java
- library/src/androidTest/java/com/github/pwittchen/prefser/library/PrefserTest.java
- library/src/main/java/com/github/pwittchen/prefser/library/Prefser.java
Removing deprecated methods for observing preferences in order to simplify the API.
> removing deprecated methods for observing preferences

- library/build.gradle
- library/src/main/java/com/github/pwittchen/prefser/library/Prefser.java
> Fix possible missed update on getAndObserve

- library/src/androidTest/java/com/github/pwittchen/prefser/library/PrefserTest.java
- library/src/main/java/com/github/pwittchen/prefser/library/GsonConverter.java
- library/src/main/java/com/github/pwittchen/prefser/library/JsonConverter.java
- library/src/main/java/com/github/pwittchen/prefser/library/Prefser.java
- library/src/main/java/com/github/pwittchen/prefser/library/TypeToken.java
Fixes #48
This PR contains interface change on raw type (i.e. `List`).
Type token issue (#44) should be fixed first.
> Introduce TypeToken and use generics for interfaces

- gradle.properties
> bumping version to 2.0.0

- gradle.properties
> bump library version to 2.0.1

- .travis.yml
- app/src/main/java/com/github/pwittchen/prefser/app/MainActivity.java
- build.gradle
- config/quality.gradle
- config/quality/checkstyle/checkstyle.xml
- config/quality/checkstyle/suppressions.xml
- config/quality/findbugs/findbugs-filter.xml
- config/quality/lint/lint.xml
- config/quality/pmd/pmd-ruleset.xml
- library/build.gradle
- library/src/androidTest/java/com/github/pwittchen/prefser/library/PrefserObservablesTest.java
- library/src/androidTest/java/com/github/pwittchen/prefser/library/PrefserTest.java
- library/src/androidTest/java/com/github/pwittchen/prefser/library/RecordingObserver.java
- library/src/main/java/com/github/pwittchen/prefser/library/Prefser.java
- maven_push.gradle
> adding static code analysis and updating project

- library/build.gradle
- library/src/main/java/com/github/pwittchen/prefser/library/Prefser.java
Added @NonNull anotations to parameters in Prefser class. I only added @NonNulls for params already checked by checkNotNull method to resolve issue #76
> NonNull support anotations for Prefser class

- .travis.yml
- app-many-observables/build.gradle
- app-preference-activity/build.gradle
- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- library/build.gradle
> updating Gradle config and dependencies

- library/src/main/java/com/github/pwittchen/prefser/library/Accessor.java
- library/src/main/java/com/github/pwittchen/prefser/library/AccessorsProvider.java
- library/src/main/java/com/github/pwittchen/prefser/library/Preconditions.java
- library/src/main/java/com/github/pwittchen/prefser/library/PreferencesAccessorsProvider.java
- library/src/main/java/com/github/pwittchen/prefser/library/Prefser.java
- library/src/test/java/com/github/pwittchen/prefser/library/PrefserTest.java
> extracting accessors to a separate class & interface - solves #109
